-- MySQL Script generated by MySQL Workbench
-- Tue Jun  3 17:54:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stagetool
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stagetool
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stagetool` DEFAULT CHARACTER SET utf8mb4 ;
USE `stagetool` ;

-- -----------------------------------------------------
-- Table `stagetool`.`gebruikers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stagetool`.`gebruikers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `voornaam` VARCHAR(45) NOT NULL,
  `familienaam` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `wachtwoord` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stagetool`.`bedrijven`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stagetool`.`bedrijven` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  `telefoonnummer` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stagetool`.`vestigingen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stagetool`.`vestigingen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  `bedrijf_id` INT NOT NULL,
  `hoofdzetel` TINYINT UNSIGNED NOT NULL,
  INDEX `fk_vestigingen_bedrijven1_idx` (`bedrijf_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_vestigingen_bedrijven1`
    FOREIGN KEY (`bedrijf_id`)
    REFERENCES `stagetool`.`bedrijven` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stagetool`.`stagementoren`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stagetool`.`stagementoren` (
  `id` INT NOT NULL,
  `vestiging_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_stagementoren_vestigingen1_idx` (`vestiging_id` ASC) VISIBLE,
  CONSTRAINT `fk_stagementoren_gebruikers`
    FOREIGN KEY (`id`)
    REFERENCES `stagetool`.`gebruikers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stagementoren_vestigingen1`
    FOREIGN KEY (`vestiging_id`)
    REFERENCES `stagetool`.`vestigingen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stagetool`.`stages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stagetool`.`stages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `stagementor_id` INT NOT NULL,
  `onderwerp` VARCHAR(45) NOT NULL,
  `beschrijving` TEXT NULL,
  `vakgebied` ENUM("INFRA", "WEB", "PROG", "ELO") NOT NULL,
  `begin` DATE NOT NULL,
  `eind` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_stages_stagementoren1_idx` (`stagementor_id` ASC) VISIBLE,
  CONSTRAINT `fk_stages_stagementoren1`
    FOREIGN KEY (`stagementor_id`)
    REFERENCES `stagetool`.`stagementoren` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
